### ISSUE TITLE
"Server is not fully started yet. Please retry" on fully started server

### ISSUE THREAD

**Issue by SyperAlexKomp** [games647/FastLogin#1220]
### What happened?

Getting disconnection with reason "Server is not fully started yet. Please retry" when trying to connect from premium account after server full load.

### Steps to reproduce

Just running server and trying to connect

### Plugin list

PlaceholderAPI, ClearLag, ServerBackup, ViaVersion, EasyAuth, WorldsColor, ProtocolLib, LuckPerms, SkinsRestorer, GSit, Geyser-Spigot, Vault, WorldEdit, FastLogin, Essentials, EssentialsChat, CoreProtect, TabList

### Configuration file

https://hastebin.com/share/fozuguxeyu.yaml

### Server log

https://hastebin.com/share/uxapekazic.makefile

### Plugin version

1.12-SNAPSHOT-bdd7af8

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
The plugin disabled itself, because of this:

>found. The server is running the latest version.
[01:58:51] [Server thread/WARN]: [FastLogin] No support offline Auth plugin found. 
[01:58:51] [Server thread/WARN]: [FastLogin] No auth plugin were found by this plugin (other plugins could hook into this after the initialization of this plugin)and BungeeCord is deactivated. Either one or both of the checks have to pass in order to use this plugin
