### ISSUE TITLE
Add an option to check if non premium players log in with premium names

### ISSUE THREAD

**Issue by lukacat10** [games647/FastLogin#155]
Possible conflict (even though the UUID is the same, a non-premium user can much more easily change its name to be the same as a premium one. An option to prevent this might be a good idea).

**Comment by games647** [comment]
> a non-premium user can much more easily change its name to be the same as a premium one

Yes, but then they will be prompted with the kick message "Invalid session. Please restart your client" if that player is already registered and enabled premium logins. If not that's still the case for enabled autoRegister, because then the plugin checks if the name is used by a premium and then assumes the player is one.
