### ISSUE TITLE
why not run in Online-Mode

### ISSUE THREAD

**Issue by LannSoros** [games647/FastLogin#165]
i want create a Online-Mode server with this plugin to do 3 things:
1,verity this player is a Online-Mode user,and send a raedom password to his email(Use Authme to do this);
2,add this player to a MySQL based Whitelist(use MySQL-Whitelist);
3.tag this player is a premium player in my MySQL Database(use FastLogin);
then i can take premium player to my Offline-Mode server with FastLogin,premium players can autologin and don't worry about account change names and items and a lot of things....based with premium UUID.
so...how can i run this plugin in a Online-Mode server to use?
Maybe i just want to run /premium @p command in this server....

**Comment by games647** [comment]
So as far as I understand you want to make an online mode lobby to verify premium player so that they can play on the offline mode server? This seems to be a bit weird since this what autoRegister already can without the need to make an extra server for that.

**Comment by LannSoros** [comment]
i want to get my players email information, and use Authme to send a readom password to thems email.
Permium users can use username/email with the password to login our website, and we can send email to our players.
Unpaid users can register a Offline account in our's website, and we will check this username not be used be a paid user.
I can't verity a paid account in web(Mojang not support a API like openid),so i must verity users in a online mode lobby.

**Comment by LannSoros** [comment]
In my country all owner run offline servers.they don't protect paid users because they don't give owner money ,but i feeled disgusting ,so i want do something to protect them.
I sawed some lines use for judgment Online/Offline Server in FastLoginBukkit.java ,but i can't build a jar file in my computer(Orz)
can you deleted them and build a jar file send to me? thank you very much.

**Comment by games647** [comment]
>i want to get my players email information, and use Authme to send a readom password to thems email.
Permium users can use username/email with the password to login our website, and we can send email to our players.
Unpaid users can register a Offline account in our's website, and we will check this username not be used be a paid user.
I can't verity a paid account in web(Mojang not support a API like openid),so i must verity users in a online mode lobby.

This goes a bit out of scope of this project. This can be done a lot easier. You only need an online mode server and check who can actually join the server. Cracked player cannot join because the session server verification will fail. 

In theory you don't even need to run a complete spigot server since it's enough to handle the login verification and kick the player immediately. Some time ago I did a [prototype](https://github.com/games647/MinecraftVerificationServer) using [MCProtocolLib](https://github.com/Steveice10/MCProtocolLib), an packet library independent from spigot. 

>In my country all owner run offline servers.they don't protect paid users because they don't give owner money ,but i feeled disgusting ,so i want do something to protect them.

Isn't AuthMe with enhanced email settings then enough for that case?  

>I sawed some lines use for judgment Online/Offline Server in FastLoginBukkit.java

What do you mean? Please explain it more.

**Comment by LannSoros** [comment]
> This goes a bit out of scope of this project. This can be done a lot easier. You only need an online mode server and check who can actually join the server. Cracked player cannot join because the session server verification will fail.
In theory you don't even need to run a complete spigot server since it's enough to handle the login verification and kick the player immediately. Some time ago I did a prototype using MCProtocolLib, an packet library independent from spigot.

I was think the same as you 3 days ago...but i think a paid user register in minecraft is a better choice.But my website is username/email based account system,so i must got player's email information..

> Isn't AuthMe with enhanced email settings then enough for that case?

hmmmm.....i mean a Full Offline Server or a Mixed Server, i choice the second one.
and i have some another way to protect paid users (offline users must register account in website,and we give them a suffix like this: http://hellomc.cc/member.php?mod=register)
in other offline servers they don't limit crack players register a paid account, so if paid account want to join this server, they must contact server owners or change them's ID,it's uncomfortable.so i give a uncomfortable choice to cracked players.

> What do you mean? Please explain it more.

in Fastlogin/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/FastLoginBukkit.java line 62 - 67:


        if (getServer().getOnlineMode()) {
            //we need to require offline to prevent a loginSession request for a offline player
            getLogger().severe("Server have to be in offline mode");
            setEnabled(false);
            return;
        }

and i want to delete this code.but i can't build a jar in mycomputer because:

![image](https://user-images.githubusercontent.com/7830924/28714324-956adaf8-73c5-11e7-8eb8-6933499c8041.png)

can you tell me how to fix it?(i'm not a Java Developer) or maybe help me build a new jar for me i see=_=!

plz forgive my bad english....thank you

**Comment by games647** [comment]
>and i want to delete this code.but i can't build a jar in my computer because:

This won't work, because the other code expect that the server is running in offline mode. Otherwise no player can join your server.

>can you tell me how to fix it?

These are only warning not errors. You can ignore those.

>in other offline servers they don't limit crack players register a paid account, so if paid account want to join this server, they must contact server owners or change them's ID,it's uncomfortable.so i give a uncomfortable choice to cracked players.

Then you would have to run FastLogin on your main server with autoRegister enabled in order to prevent any cracked player to register a premium account. 

>and i have some another way to protect paid users (offline users must register account in website,and we give them a suffix like this: http://hellomc.cc/member.php?mod=register)

So cracked players have to register online and premium players only in Minecraft?

**Comment by LannSoros** [comment]
well....maybe i can try to write a plugin to make a MySQL record lol

> So cracked players have to register online and premium players only in Minecraft?

yes! premium players can finished every job in Minecraft client; and cracked player must register account in website.

**Comment by LannSoros** [comment]
i think i know how to finish my problem:
1.start a verity lobby, and open AutoRegister in FastLogin;
2.player join this server to verity paid account and AutoRegister, but i don't use this register data;
3.now this player can join my Offline Server with a paid UUID, and he can do next step in my Offline server;
anyway, thank you reply me and write this great plugin!
