### ISSUE TITLE
SkinsRestorer change skin for premium

### ISSUE THREAD

**Issue by Feerko** [games647/FastLogin#184]
### What behaviour is observed:
SkinsRestorer works for only non-premium players

### What behaviour is expected:
Change skin for premium players

### Plugin list:
SkinsRestorer

### Configuration:
https://pastebin.com/raw/geBaZTMz

**Comment by games647** [comment]
Note: I **assume** you use BungeeCord here. Please fill the template completely next time.

There is nothing I can change here. FastLogin sets the skin very early to let other plugins actually change, so SkinsRestorer has to fix it. 

I already reported a similar bug (Th3Tr0LLeR/SkinsRestorer---Maro#132, Th3Tr0LLeR/SkinsRestorer---Maro#151) with hints to fix it. It worked after that. It looks like they broke it again.

**Comment by xknat** [comment]
@games647 we did fix the issue in 13.0.1 and 13.0.(7/8) by delaying the skins a bit to it will apply after mojang premium skins and in 13.0.8 we did add a softdepend so it would detect what world it is on for dimension & worldscale otherwise it won't apply right or smth..

but Feerko was using alternative a multi world  so it broke down, will work on it :)
thanks for the reference~
xknat
