### ISSUE TITLE
Problem Minecraft Skin Overlay

### ISSUE THREAD

**Issue by JoaoCosta52PT** [games647/FastLogin#187]
### What behaviour is observed:
Player skins don't show the overlay.

### What behaviour is expected:
The player skin overlay should appear but it doesn't.

### Steps/models to reproduce:
When I enter my server the overlay of my minecraft skin, it does not appear.
But if you enter the server mc.hypixel.net or any other my skin displays the overlay.

Here is a Screenshot of my skin on my server and on Hypixel.

Photos on my server (Skin Overlay is missing)
https://imgur.com/ix2JydV
https://imgur.com/Biekmmp

Photos on Hypixel (Skin overlay is there)
https://imgur.com/EB3K6cn
https://imgur.com/w4CCTXf

### Plugin list:
ViaVersion and FastLogin

### Environment description
BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:0fc5694:1278

### Plugin version or build number (don't write latest):
1.10-git484855724b794de1fe057cf7360245362658b432

### Error Log:
There are no errors in the Console.

### Configuration:
https://gist.github.com/JoaoCosta52PT/588cdcdf345b0a238351544964adacca

**Comment by games647** [comment]
Could you check your client settings, because skins are always send completely (including the cape data). There is no way to change something in it. Furthermore in BungeeCord integration in FastLogin is very simple, because we could enable online mode with a single method call. Everything else like validation, skins and UUID is handled by BungeeCord. We only override those properties if you disable premiumUUID or forwardSkin.
