### ISSUE TITLE
Offline Premium Player uuid Detection

### ISSUE THREAD

**Issue by Blackyvk** [games647/FastLogin#24]
Basically there are plugins like [OpenInv](http://dev.bukkit.org/bukkit-plugins/openinv/) which let me check players inventory  when they are offline... because the server is offline  mode, we cannot use this kind of feature for offline premium players because I believe the plugin will try to find a player with a cracked uuid unless he is online. Is there a way to do fix it with fastlogin ?

other plugin that has this issue is [QuickShop](http://dev.bukkit.org/bukkit-plugins/quickshop-notlikeme/)

**Comment by games647** [comment]
I think the same problem would occur if the server is in online mode and we want to check the inventory of a cracked player. A idea is to give the cracked player a premium uuid (faked).

**Comment by games647** [comment]
I looked at the source code of OpenInv. OpenInv makes a lookup against the Mojang servers if the server is in online mode. Otherwise it will make a cracked only check. 

So I see the following options here:
* Give cracked players a premium UUID with the risk that the premium player cannot join the server although the premium player changed it's name
* Disable premium uuids, but premium players will loose their items, ... if the change their name
* Implement a constant uuid and addition to the option above. Premium players will receive a cracked uuid based on their name. If they change their names, FastLogin will remeber those players and will give them the old cracked UUID back.

What's the problem with QuickShop.

**Comment by Blackyvk** [comment]
with quickshop you cant use this command /qs setowner offlinepremiumplayer 

I think its better not to do it, i like FastLogin how it is right now, i was just wondering if there was an easy fix for this, maybe i should ask the dev of openinv if he can make it compatible with fastlogin or else I will see if i can "patch" openinv myself somehow, not that i know how but I'll try.

Thanks!

**Comment by games647** [comment]
Of course, no problem.
