### ISSUE TITLE
mysql not work

### ISSUE THREAD

**Issue by mat41997** [games647/FastLogin#25]
config
http://pastebin.com/7rtsCUnb

timings
https://timings.aikar.co/v2/?id=02ec3fe144754a0ba672202a0925da12

plugin not work

**Comment by games647** [comment]
Please explain it more.

**Comment by mat41997** [comment]
full logs
http://pastebin.com/US8B76fx

**Comment by games647** [comment]
And what exactly doesn't work?

**Comment by mat41997** [comment]
all the plugin

**Comment by mat41997** [comment]
![1](https://cloud.githubusercontent.com/assets/5884000/15985739/8648e2b2-2ff7-11e6-92b0-4a5036eaf42f.png)

**Comment by games647** [comment]
It works for me absolutely fine. Are you sure the player instance is premium the database.

**Comment by mat41997** [comment]
yes
![2](https://cloud.githubusercontent.com/assets/5884000/15985764/4ef458ea-2ff8-11e6-906e-7ba80e6a7d2c.png)

**Comment by games647** [comment]
Can I see a pic of the database?

**Comment by mat41997** [comment]
![3](https://cloud.githubusercontent.com/assets/5884000/15985771/7f8d3508-2ff8-11e6-84c4-3cbe248680fd.png)

**Comment by games647** [comment]
The MySQL database...

**Comment by mat41997** [comment]
[mysql.zip](https://github.com/games647/FastLogin/files/310309/mysql.zip)

**Comment by games647** [comment]
A picture would be enough.

**Comment by mat41997** [comment]
![a2](https://cloud.githubusercontent.com/assets/5884000/15985818/d56771ea-2ff9-11e6-8d77-d13805c5da15.png)
![a3](https://cloud.githubusercontent.com/assets/5884000/15985819/d56bc0a6-2ff9-11e6-9036-d2f9c30e3a97.png)
![a1](https://cloud.githubusercontent.com/assets/5884000/15985820/d56fbe18-2ff9-11e6-827c-1ed225ec68af.png)

**Comment by games647** [comment]
As you can see. There is no data in the database.

**Comment by mat41997** [comment]
![b1](https://cloud.githubusercontent.com/assets/5884000/15985827/23cdb862-2ffa-11e6-87d0-e13a1a40f68b.png)
![b2](https://cloud.githubusercontent.com/assets/5884000/15985826/23c99b88-2ffa-11e6-93af-81b6da334615.png)
![b3](https://cloud.githubusercontent.com/assets/5884000/15985828/23d06e2c-2ffa-11e6-8103-f5e00de3f8ac.png)

**Comment by games647** [comment]
Table rows = 0

=> No data in it.

**Comment by mat41997** [comment]
![c1](https://cloud.githubusercontent.com/assets/5884000/15985851/a7b8f614-2ffa-11e6-9b75-dc6995301eef.png)

**Comment by games647** [comment]
If you previously used SQLite, you have to import those data.

**Comment by sgdc3** [comment]
@games647 please, reopen this and explain what do you mean

**Comment by games647** [comment]
I thought it's fixed.

**Comment by games647** [comment]
**Short description**
Based on the picture here: https://cloud.githubusercontent.com/assets/5884000/15985827/23cdb862-2ffa-11e6-87d0-e13a1a40f68b.png

It says table rows: 0. It means there is **no data** in the database. I'm assume he switched from SQLite to MySQL. Because MySQL doesn't have the data from SQLite, FastLogin doesn't know anything about this player. So the data have to be imported or every player who is premium has to type /premium. 

In order to migrate the database, you can use tools like SQLiteman. Open the .db file with that program, and select dump database. Then remove the "create table"- and "pragma"-commands. Then You can just copy paste that into MySQL query executor. (Available in PHPMyAdmin and MySQL Workbench as well)

**Longer description:**

I never received any information if the there is actual data in the database. I have seen that database structure was created and FastLogin makes connections to the database. So I assume @mat41997 switched from SQLite to MySQL. If there is no data in the MySQL database FastLogin doesn't know if the player is premium, because this data is in the SQLite database.

Although FastLogin sees that the player uses is premium, it notices that this player is already registered (because of FastLogin with the old database). In order to protect pure cracked players from stealing accounts, FastLogin will save the joined player as cracked. If it's the same person, he/she can turn on auto logins after logging in to proof that they are the owners of the cracked account on this server too.

I implemented this to make sure there will be no security risk for both types of players. (Cracked and Premium). 

In the case you deactivated for a while, you can even use the plugin without any risks. Even if you installed it on a fresh server, migrated the login plugin (i.e. AuthMe) database to FastLogin and missed one entry or failed to perform some installations steps, FastLogin make additional checks to prevent security vulnerabilities.

I want to help @mat41997 , but the problem is that I didn't received the data I requested. [I asked for a description](https://github.com/games647/FastLogin/issues/25#issuecomment-225368138) and just received the server log.

Later on ["all"](https://github.com/games647/FastLogin/issues/25#issuecomment-225368582), this is really not a good description. Does it happen for new players? What about complete new usernames? Do you tried to invoke the premium command? Could you try it with turn off autoReg? Can cracked players still join the server? Any debug data?

Does it happen on reload? 

**And of course what happened earlier? Do you switched to MySQL?**

Then I received no answer on [my last response ](https://github.com/games647/FastLogin/issues/25#issuecomment-225370311) Just a dislike, **no reason** If you think by closing the issue ticket, I want to ignore you. You are completely wrong. **I closed it, because I thought this reason for this issue.** 

If you had responded with things like:
- Still not fixed
- How to do that?
- I tried that, but still doesn't work?

**I would reopen the issue ticket as I see the problem is not fixed and still want to help you.**
