### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [games647/FastLogin#259]
Hi
The following lines have cryptographic API misuses. <br> File name => bukkit/src/main/java/com/github/games647/fastlogin/bukkit/EncryptionUtil.java: Line number => 108: API name => Cipher:<BR> File name => bukkit/src/main/java/com/github/games647/fastlogin/bukkit/listener/protocollib/VerifyResponseTask.java: Line number => 83: API name => Cipher:Unexpected call to method init on object of type javax.crypto.Cipher. Expect a call to one of the following methods update,doFinal<BR> File name => bukkit/src/main/java/com/github/games647/fastlogin/bukkit/EncryptionUtil.java: Line number => 113: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => bukkit/src/main/java/com/github/games647/fastlogin/bukkit/EncryptionUtil.java: Line number => 94: API name => SecretKeySpec:<BR> File name => bukkit/src/main/java/com/github/games647/fastlogin/bukkit/EncryptionUtil.java: Line number => 94: API name => SecretKeySpec:<BR> File name => bukkit/src/main/java/com/github/games647/fastlogin/bukkit/EncryptionUtil.java: Line number => 108: API name => Cipher:<BR> File name => bukkit/src/main/java/com/github/games647/fastlogin/bukkit/EncryptionUtil.java: Line number => 119: API name => MessageDigest:<BR>

**Comment by games647** [comment]
Thanks for creating this automated report, but a lot of details are missing. Only two errors have a description. I don't know what you mean with the other things. 

Then also your tool complains about SHA-1 (I **guess** because of the hash conflicts), but I'm unable to change that since this is dependent on the original Mojang in this case.

Regarding the first/second? point, it's now fixed by initializing the key only once. Thanks for pointing that out.
