### ISSUE TITLE
Updated for 1.14.3

### ISSUE THREAD

**Issue by 1337god** [games647/FastLogin#261]
Hello, when is the update for 1.14.3? I haven't tried, but wanted to make sure it's either compatible with it first, if someone have already tested it or if it's on the works.

**Comment by games647** [comment]
It's already compatible. You can expect only small changes if the minor version number changes. (example format: Major.Minor.BugFix). Furthermore the login mechanism is very stable, so we even expect only no or minimal changes between major versions too. 

More important is the protocol implementation FastLogin uses. These are ProtocolSupport and ProtocolLib in Spigot only mode and BungeeCord. Those plugins have to be compatible with the new version. That's the currently the case, but you can expect that those plugins have to be updated if the major version of Minecraft changes, because writing raw packets is heavily dependent on the current version.
