### ISSUE TITLE
Add McAPI - Hit rate-limit when many players join the server

### ISSUE THREAD

**Issue by Feerko** [games647/FastLogin#27]
Hello,

Can you add support for mcapi? 
During live YouTuber on my server is overloaded api Mojang. A lot of new people joining to the server and api server stops responding.

**Comment by games647** [comment]
According to their issue tracker McAPI has issues with rate-limiting too:

https://github.com/MCAPI-CA/Issues/issues/20

**Comment by games647** [comment]
I have the same problem with ChangeSkin ([the post on the forums](https://www.spigotmc.org/threads/changeskin.138380/page-5#post-1649746)). Although both plugins checks hits the Mojang only for new players it's got rate-limited. Moreover a in-memory cache is implemented and it tries to ask the local database first before querying Mojang.

**Comment by games647** [comment]
Another solution would be to request always a online mode authentication and if the player cannot join the server, FastLogin can notice that and login the player in offline-mode next time, but I think this is a bad user experience, because there is no way to change the disconnect message "Invalid session".

As a solution you could disable nameChangeCheck and autoRegister. Then all players will be logged in as cracked and turn premium authentication later on. 

Another suggestion I have is that the plugin first tries to hit the Mojang and if it fails, it will make for the next ten minutes always a cracked authentication. Then makes request to Mojang again.

PaperSpigot is implementing a global server-wide [UUID-Cache](https://github.com/PaperMC/Paper/pull/309). Maybe that could help if multiple plugins are requesting the same information. 

All the third-party APIs seems to have the same rate-limiting issues although they use multiple IPs. Another solution I can imagine is that big server networks have to pay a service or buy multiple IPs, so that FastLogin and other plugins will not hit the rate-limit.

**Comment by games647** [comment]
@sgdc3 I'm online there.

**Comment by Feerko** [comment]
I'm sorry for my English . This is not my native language.

> Another solution would be to request always a online mode authentication and if the player cannot join the server, FastLogin can notice that and login the player in offline-mode next time, but I think this is a bad user experience, because there is no way to change the disconnect message "Invalid session".

I agree

> As a solution you could disable nameChangeCheck and autoRegister. Then all players will be logged in as cracked and turn premium authentication later on.

> Another suggestion I have is that the plugin first tries to hit the Mojang and if it fails, it will make for the next ten minutes always a cracked authentication. Then makes request to Mojang again.

I think it's not a good idea. Plugins using uuid lose data for premium because uuid will be changed.

> All the third-party APIs seems to have the same rate-limiting issues although they use multiple IPs. Another solution I can imagine is that big server networks have to pay a service or buy multiple IPs, so that FastLogin and other plugins will not hit the rate-limit.

My dedicated server has five IP addresses. To be honest, I do not know if the plugin uses only one ip or all. I check it out tonight.

Even so, I think that the use of mcapi is good. When Mojang unresponsive, a lot of people will be registered.

**Comment by Feerko** [comment]
Refresh

**Comment by sgdc3** [comment]
@games647 is working on his own caching system, please wait for new updates ;)

**Comment by games647** [comment]
The problem I have with MCAPI is that MCAPI has rate-limiting issues to and if a request failed because of it. They return a result as it is a cracked player although they don't know it. 

That's **not** a good practise, because it's error-prone.
=>Ends up in a situation like you described
>I think it's not a good idea. Plugins using uuid lose data for premium because uuid will be changed.

Even the example from the website shows uuid=null -> cracked although a lot players are requesting this example
https://mcapi.ca/uuid/player/Yive

or using the hasPaid API:
https://mcapi.ca/other/haspaid/games647

This a big no-go for me. 

I've contacted
* https://craftapi.com/ over twitter -> no reply ;(
* http://uuid.turt2live.com/ -> bad performance 
* https://mcapi.de/ -> author wrote me that he started after I sent him asked him about that
* https://us.mc-api.net -> returns a cracked response too on failure, but I **guess** they doesn't seem to be hit by rate-limits

In my opinion it's ok if the result is even cached since a day or longer. It's really rare situation where a recently bought user accounts joins the server. This is why I started the other project.

@Feerko But this other projects needs some time. As I don't want you to wait longer, I would implement https://us.mc-api.net/ if that's okay for you?

Another suggestions which comes to my mind is the following:
1. Premium check failed, because of rate-limit
2. Players joins as cracked (but is the owner of the minecraft account)
3. Player invokes /premium
4. Instead of receiving the premium UUID, the plugin will keep both UUIDs
(premium and username cracked UUID)
5. Player will always receive the cracked UUID
6. In the case player changes it's name -> plugin will see the premium UUID
7. Plugin will attach the old cracked UUID to the player
=> Player keeps the cracked UUID even after name changes

Cons:
1. Premium player will receive a cracked UUID
2. UUIDs are named based -> after name change, cracked UUID of the **old name**
Could cause conflicts in plugins which depends on this

**Comment by games647** [comment]
>My dedicated server has five IP addresses. 

If that's really the case. I could look into it how to force Java to make use of all the IP-Addresses. 

normal rate-limit:
600 request per 10 minutes (or 60 per minute)

In your case:
5 * 600 requests per 10 minutes (or 5 * 60 per minute)
=>3000 per 10 minutes (or 300 per minute)

And these requests are only necessary for new players. I'll look what I can do.

**Comment by games647** [comment]
@Feerko Do you use BungeeCord?

**Comment by Feerko** [comment]
>But this other project needs some time. As I don't want you to wait longer, I would implement https://us.mc-api.net/ if that's okay for you?
>If that's really the case. I could look into it how to force Java to make use of all the IP-Addresses.

Would be great. Thank you for taking me your time.
Yes, I'm using Bungee.

**Comment by games647** [comment]
>If that's really the case. I could look into it how to force Java to make use of all the IP-Addresses.

Sorry for the delay. I looked it up for hours how to do it. I asked in forums, stackoverflow, ...Now I found a solution.

**Comment by Blackyvk** [comment]
I just tried it  and got timed out trying to login.
http://pastebin.com/8RSxjGWL

then after a while

http://pastebin.com/JCqH8m4w

I just dont know if its a hosting problem now since...  how can I be sure before you open again this issue?

**Comment by games647** [comment]
It's my mistake. Sorry. It was a self invocated method without a ending.

**Comment by Blackyvk** [comment]
I got the same output... I'll try with the plugins needed to load fastlogin.... I still believe this host is the problem, i wont recommend it to anyone.

**Comment by games647** [comment]
Could you show me the new error?

**Comment by Blackyvk** [comment]
i had to wait a while for the error to show up.

**Comment by games647** [comment]
Are you sure you have the version after the commit I made? 

Could you do "git rev-parse HEAD" in that folder?

**Comment by games647** [comment]
Could you try it again?

**Comment by Blackyvk** [comment]
:/ the same... is there a way to see if its my server hosting ?

http://pastebin.com/WxeFucem

**Comment by games647** [comment]
I really fixed it the commit and is a mistake made by me. Line 124 no longer points to the same method , it points to getUUIDFromJsonAPI
