### ISSUE TITLE
AntibotDeluxe 10 Compatibility

### ISSUE THREAD

**Issue by xion87** [games647/FastLogin#292]
I notice when using AntibotDeluxe (https://www.spigotmc.org/resources/antibotdeluxe-%E2%80%BA-the-most-advanced-antibot-spigot-bungee-1500-purchases-1-7-1-15.31700/) i keep my console spammed with fastlogin messages
https://gist.github.com/xion87/183b2d021ab660b665a4715fadd66875

Where is wrong? (bungee mode)

**Comment by games647** [comment]
Do you have the `switch-kick-message` key in your locate settings inside the FastLogin BungeeCord folder?

**Comment by xion87** [comment]
i don't have it

**Comment by xion87** [comment]
i mean yes
# Switch mode is activated and a new (non-whitelist) cracked player tries to join
switch-kick-message: '&4Solo i giocatori Premium in Whitelist possono entrare nel server'

**Comment by games647** [comment]
I made some changes in the latest commit to set the kick reason on the event instead of using the generic kick method. However the error is about having null in the reason text for kicking. Switch mode is the only reason to kick in this event from FastLogin.

**Comment by xion87** [comment]
but it happened only with latest version of antibotdeluxe (version 10+) i never see that error ^^, i try to update and see

**Comment by xion87** [comment]
the error seem gone from the version with your patch :)

**Comment by games647** [comment]
Nice

**Comment by xion87** [comment]
got a huge bot attack right now, look the console how it look
![image](https://user-images.githubusercontent.com/3611852/72179488-47010d00-33e5-11ea-8c99-9ee87646ad46.png)

**Comment by games647** [comment]
Then I think you should contact the author of AntiBotDeluxe. Based on previous mentioned stuff, I believe FastLogin is not the source of this error. You see FastLogin in this case, because FastLogin tells the event to halt the execution, processes something in the background and then later tells the event to continue. Other plugins could process the event in the meanwhile

>at net.md_5.bungee.api.event.AsyncEvent.completeIntent(AsyncEvent.java:86)

FastLogin is the last plugin that releases this lock (internally implemented as a countdown) and therefore shows up the stacktrace.
