### ISSUE TITLE
Offline UUID based on username provided by client (outdated after name change)

### ISSUE THREAD

**Issue by xion87** [games647/FastLogin#344]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
Some players reported after name changes will still have the same item/inventory, i checked and i say the old name uuid and new name uuid are recognized as the same, doing /cracked and /premium again will fix the the uuid Note: i am not using premium uuid (i believe is happening only to new names, old ones are not affected)

after they changed the name on my network and relogin with the new name (after /premium) they will have the same uuid of the old offline name

### What behaviour is expected:
The new "premium" name should have the correct uuid 

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
- join on offline nework 
- do /premium
-  change the name in one never used 
- do /premium
- you will have the uuid of the old name

### Environment description
Waterfall offline mode

### Plugin version or build number (don't write latest):
[//]: Build 924 from jenskin installed on waterfall, login server and hub servers

### Server Log:
No errors (oly a complain from luckperms saying the name of that person is changed but uuid is changed)

### Configuration:
https://gist.github.com/xion87/c8ec62629fac5881809881cdb2cd3e1d

**Comment by games647** [comment]
That's strange, because the UUID FastLogin sets is always retrieved from the current online mode request. In this case in doesn't use any stored data. Could you post that log message from LuckPerms? Maybe it's related to #319 and could also help here.

**Comment by xion87** [comment]
The luckperms error: (on bungee) https://gist.github.com/xion87/55f508b10457225477288694f470e932
The same uuid log on all bukkit: https://gist.github.com/xion87/a5e812ae376f053fe843c6b16999aeda

**Comment by games647** [comment]
LuckPerms:
How does LuckPerms get the first UUID? That's not even a correct UUID registered at Mojang. The second UUID it sees is the correct offline UUID. That's expected, because LuckPerms should listen to events after FastLogin. Could you test it with debug logins of LuckPerms. Then it will print the first UUID it saw.

Same UUID. 
If you have BungeeCord enabled, this could occur during forwarding the message to Spigot (FastLogin doesn't interfere here) or on setting the offline UUID there. I added some logging calls that should help to find the source.

**Comment by games647** [comment]
BTW: Which version of LuckPerms do you use and do you use any other UUID changing plugins?

**Comment by xion87** [comment]
I don't use any other plugin that edit uuid, i use on bungee and luckperms LuckPerms-Bungee-5.0.130
I have these plugin on bungee:
![image](https://user-images.githubusercontent.com/3611852/82050614-b8650b00-96b8-11ea-8000-fc6def1155e2.png)

**Comment by games647** [comment]
Okay LuckPerms only the build number in their version. That's a little to difficult to trace any relevant changes back. I made the log message much more expressive in the most recent commit. This is a very critical issue in my eyes. Does it happen very often?

As I said earlier this is very strange. FastLogin extracts the relevant data for UUID changing only from the firing `LoginEvent` and that even completely synchronous.

**Comment by xion87** [comment]
it happen often yes...
i updated fastlogin now and i get messages like
>.... [08:39:10 INFO] [FastLogin]: Overridden UUID from 66793ef6-89bd-45ad-bc3f-a6d12d33e452 to 70aa72f0-0af4-3d76-92ed-b3075d133ba2 (based of M4st3rBr0g) on [/151.62.53.16:54871|M4st3rBr0g] <-> InitialHandler
>.... [08:39:10 INFO]: [M4st3rBr0g|/151.62.53.16:54871] <-> ServerConnector [login] has connected

**Comment by games647** [comment]
>It can be some other plugin at bungee that acting weird with fastlogin premium?

Could be, but I wonder why. Everything seems to set correctly. I also added a check that verifies that after the reflection call the UUID is visible. Everything else is left untouched. After this FastLogin does no more modifications. Maybe something went wrong while BungeeCord forwards this message or on Spigot's end, but this fairly standard and FastLogin doesn't interfere with any of it.

However the LuckPerms error seems to indicate that this error is originated in BungeeCord. **Could you enable debug logins for LuckPerms?** That should enable printing the UUID it first sees. Also do you see the first UUID earlier: '9dd2afc5-b968-39e5-95bf-cb4b34967113'. **Could that be the UUID from someone else?**

I also tried to look at threading issues, because of parallel access to variables, but that doesn't seem to be the case. Also that it happens often means it means to be caused by something else.

**Comment by xion87** [comment]
Sorry again i speaked with my helper that explained me better how is happened
1) He changed the nick on mojang ok
2) He logged on my server and registered the account with authme
3) After he login with the new account he noted he have the premium enabled and almost all stuff transfered (inventory, rank ecc except for plots)
I attach here the full logs on bungee and login server, my helper nick was **VinciPM** and the new name **71584**
[logs.zip](https://github.com/games647/FastLogin/files/4643584/logs.zip)

> However the LuckPerms error seems to indicate that this error is originated in BungeeCord. Could you enable debug logins for LuckPerms? 
ok done that i will post result later

> That should enable printing the UUID it first sees. Also do you see the first UUID earlier: '9dd2afc5-b968-39e5-95bf-cb4b34967113'. Could that be the UUID from someone else?
I investigated that case it was because on the past the loged the same name in different case, please ignore the past log of that player but look the case of my helper

**Comment by xion87** [comment]
happened today
[latest.zip](https://github.com/games647/FastLogin/files/4672577/latest.zip)
The player MAXI2134 have change his name to PastaAsciutta_

**Comment by games647** [comment]
Did it happen about 21:44? Well there I could see this:

>247993 [21:44:36] [Netty Worker IO Thread #70/INFO] [FastLogin]: Overridden UUID from 5aa9b086-bda6-4686-9dca-62d187388ad8 to cad9fdc1-467b-3973-a254-3e281d0f9753 (based of MAXI2134) on [/79.7.195.228:63690|PastaAsciutta_] <-> InitialHandler
247994 [21:44:36] [Netty Worker IO Thread #70/INFO] [LuckPerms]: Processing pre-login for cad9fdc1-467b-3973-a254-3e281d0f9753 - PastaAsciutta_
247995 [21:44:36] [LastLoginAPI Pool Thread #170/INFO]: [^[[33mLastLoginAPI^[[0m] Get player request for 'cad9fdc1-467b-3973-a254-3e281d0f9753'
247996 [21:44:36] [LastLoginAPI Pool Thread #170/INFO]: [^[[33mLastLoginAPI^[[0m] Update player for PastaAsciutta_ [cad9fdc1-467b-3973-a254-3e281d0f9753]
247997 [21:44:36] [Netty Worker IO Thread #70/INFO] [LuckPerms]: Processing post-login for cad9fdc1-467b-3973-a254-3e281d0f9753 - PastaAsciutta_
247998 [21:44:36] [Netty Worker IO Thread #70/INFO]: [PastaAsciutta_|/79.7.195.228:63690] <-> ServerConnector [login] has connected

It sets on the correct connection, but the based username is incorrect. It actually happens multiple times before it. .... Oh I think I know what's happening here. If you change the username, your client might not notice that change and will still send the request using the old username. That's very interesting. I could fix that by using on the data provided provided by the Mojang response instead of relying on the userdata.

**Comment by xion87** [comment]
> Did it happen about 21:44? Well there I could see this:

Yeah it happened to that hour

>  I could fix that by using on the data provided provided by the Mojang response instead of relying on the userdata.

Do it please ^^, that bug is super anoying

**Comment by games647** [comment]
>Do it please ^^, that bug is super anoying

Started working it immediately after writing ;)
