### ISSUE TITLE
Mojang Eula compliance

### ISSUE THREAD

**Issue by yassinrais** [games647/FastLogin#375]
hello team :) 

i have question about eula mojang

Its is danger the plugin for our server : mojan eula online-mode blacklist

? 

thanks

**Comment by games647** [comment]
I'm not a lawyer. This is how I interpret the EULA.

The only relevant part seems to be: `or make [the game] available for access to other people` This depends on how "the game" is defined, because we only provide access to a server. Furthermore, this access only switches the onlinemode on and off that is already provided in the vanilla version. Every public offlinemode server could then be against the EULA. This plugin only switches the online mode on and not off. 

So in my opinion the use of this plugin specifically is not problematic, but rather the offlinemode itself. From my quick search other people have a similar understanding.

**Comment by yassinrais** [comment]
mmm ok .. i agree about what you say !

but the question how the client detect online mode ? 
its the plugin use the same way as _server.properties_ (i mean is the plugin do same job as the online mode checker default) ?
for example 

in a class you have constructor ( and the constructor is the first one who is launched )
is the plugin has the same thing as the origina online mode check ?

**Comment by games647** [comment]
The client detects online mode based on if we send a encryption request packet. This will request the client to authenticate to Mojang. In offline we would send a login success packet directly. FastLogin's implementation is different, but the packet flow is the same.

**Comment by yassinrais** [comment]
Okey ! i understand 
thanks for the explanation :D
