### ISSUE TITLE
Premium players are'nt premium (Bungee)

### ISSUE THREAD

**Issue by Tim-NL** [games647/FastLogin#46]
Hello, 

I'm using the latest version from Spigot and I have enabled; AutoLogin, PremiumUUID and NameCheck. But a premium player is still set as a cracked player. (No UUID in the DB and Premium is set to 0). I'm using BungeeCord. 

So I have been looking for the reason and i found this commit; 
https://github.com/games647/FastLogin/commit/a6348766b3a8fe5b20ece9f9a269c48dcb0e398b

After reverting this commit in my fork everything started working again. So I think there is a mistake in there. 

~
Tim

**Comment by games647** [comment]
Do you installed the plug in correctly on the bungee server. It sets it only premium if the bukkit module accepted it and did a force register. (Not registered before)

**Comment by games647** [comment]
The problem on your version (the fork) is that it will proöarly make an premium authentication for every cracked player. A bug that I noticed only later. 

It's only a guess, beca use I'm writing this on my phone.

**Comment by Tim-NL** [comment]
If you can check it out later? I tryed a lot of things and it only seems to work when I revert that commit. I didn't test anything for cracked players yet so I don't know if a cracked player will be flagged as premium.

**Comment by Tim-NL** [comment]
Great, its working now ;) 

And this is correct? https://github.com/games647/FastLogin/blob/master/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/listener/protocolsupport/ProtocolSupportListener.java#L52

Or should it be; !isRegistered like the the ProtocolLib NameCheck class.

**Comment by games647** [comment]
Good point. I thought I already did that.

**Comment by TheClub-Network** [comment]
Hello, I'm having the same issues. @games647, I thought you already fixed it but How can i download the DEV build version of this fixed. Could you provide me the link if available. Sorry for my stupid. :(
Thanks.

**Comment by games647** [comment]
From here: https://www.spigotmc.org/resources/fastlogin.14153/update?update=107647

**Comment by games647** [comment]
^^ The dev-builds are normally located at here: http://ci.xephi.fr/job/FastLogin/changes

But they are only built on AuthMe changes.

**Comment by TheClub-Network** [comment]
Awesome !!! Thanks for your updated. I check it out now. Millions Thanks.

**Comment by TheClub-Network** [comment]
Hello, Alright, I tested several times with the 1.7.1 updated
https://www.spigotmc.org/resources/fastlogin.14153/update?update=107647 
but still having the issues on autoRegister don't work properly.

Steps to reproduced 
1. drop and re-create authme and fastlogin database.
2. delete player data and stats folder in the world folder.  
3. log on the server at first time and found that autoRegister won't work I need to /register command with password.
This point any new premium player data will not create in the fastlogin table and they don't autologin until they invoke /premium command. I think it is really annoying.

The way to make this autoRegister to work, After couple times test and I founded that when you log on the server at first time you have to log off immediately without do /register command and then rejoin Boom autoRegister will work. I have no idea now.

PS. I reproduced for 1 and 2 steps above before test.

Thanks for reading.

**Comment by Tim-NL** [comment]
Works fine here @TheClub-Network 

Can you check if; 
- You have AutoRegister true in the config? (Bungee & Spigot (not sure if they are both needed but just to be sure))
- The stats ID from the bungeeconfig is in the whitelist file in the Fastlogin folder? 
- Does the bungee plugin work? (Are you using MySQL, SQL won't work by default).

**Comment by TheClub-Network** [comment]
@Tim-NL 
- Yes, Here is my config http://pastebin.com/fwiqq2rw
- Yes, I added bungeecord stats to proxy-whitelist.txt file
- I've been using FastLogin since 1.6.x till now and I'm using MySQL.
![screen shot 2559-08-02 at 0 06 27](https://cloud.githubusercontent.com/assets/20353071/17302181/2ed2c6a8-5845-11e6-96e6-09b1e1345f0f.png)

But after a few tested and now its work.
Maybe this might cause an issue by slow internet connection, seems like bungeecord/server can't connect to Mojang authentication server or mcapi, Anyway I re-testing again with good internet connection and Its work now, I really have no idea what exactly caused the problems.

@games647 What do you think? and I noticed that the latest updated 1.7 - 1.7.1 won't generating the new config file. This might cause some lazy people have a question where is new feature configuration if they didn't read it.
# You can access the newest config here:
# https://github.com/games647/FastLogin/blob/master/core/src/main/resources/config.yml

Thank you guys.

**Comment by games647** [comment]
>bungeecord/server can't connect to Mojang authentication server or mcap

Recently mcapi was down. Maybe you were affected by this.

>@games647 What do you think? and I noticed that the latest updated 1.7 - 1.7.1 won't generating the new config file. This might cause some lazy people have a question where is new feature configuration if they didn't read it.

Line 5 and 6 should show how they can access the new config. It's very difficult to make a configuration where new keys will be added automatically. That's why I decided to not do that.

**Comment by games647** [comment]
Good point

I didn't thought it would happen, because I never noticed that mcapi goes down and I thought that Mojang servers are more stable.

FastLogin makes only requests to mcapi if the rate-limit is reached, so mcapi will only be used if the server makes more than 600 name->uuid requests per 10 minutes (FastLogin makes those only for unknown players).
