### ISSUE TITLE
AutoRegister support for cracked with premium names.

### ISSUE THREAD

**Issue by lizardfreak321** [games647/FastLogin#51]
In my server setup, I am basically trying to hide the fact that I accept Cracked players, therefore premium players need to be auto-registered, but in this plugin to achieve that I need to also reject cracked players with the name of a premium player. Many of the cracked players on my server use premium names, and therefore I cannot use that mode, which creates a conflict.

The other option would be to disable auto-registration. That mode is perfect for the cracked players, but the premium players automatically join as a cracked player which causes issues, since my players don't like to enter the commands they are told to by the server, so countless premium players will play with the incorrect UUID until we tell them to do /premium, which is a horror I do not want to happen. It will also make it very obvious that we are a premium server, which makes some players think negatively of my server.

The solution is not perfect, but it should work pretty well, so I think it should be a config option.
Here it is: after failing the premium encryption request (So PreLoginEvent without a LoginEvent following it after the 5 second timeout), it records their username as failed auth check (Maybe a 3 in the database). Next time they join it will allow them to join in offline mode. The third time they join it will do a second online mode check again, and if they fail a second time it will log them as cracked. The second check will be after a delay (maybe a day) to prevent it from falsely assuming they are cracked after the first encryption request failed because their first time joining they may have had an expired session.

To prevent further false assumptions, also check if the session and/or auth servers are online in case they started Minecraft in offline mode (which would create a false session) or if it failed because the mojang servers are down and _not_ because they were in offline mode.

The way I just described will be a lot better than the current setup I use (Which is terrible because the dev didn't know how to register an intent and instead used a blocking operation which causes pauses to players) and because of all of the checks and logging I am describing. My current plugin doesn't log anything but the names that are premium. I was actually planning on making a plugin if I had time but after I saw this I decided someone already did the work. If you cannot implement this feature I guess I will just edit the one I have (Which I was able to decompile because it broke when Mojang's website changed) and fix the blocking operation, but your plugin is significantly better.

Thanks for reading this, let me know if anything doesn't make sense.

**Comment by games647** [comment]
Sorry for the late response. I was in vacation for 4 days and did only minor things. 

So basically you want an option that checks if the first premium authentication attempt failed. If the player makes another one login the player as cracked. Do I understand that correctly?

I'm thing of a in-memory 5 minute cache that remembers the attempts of the unknown players. What do you think?

**Comment by lizardfreak321** [comment]
A 5 or 10 minute cache sounds good.
After they log in as "failed" because of the cache, I think it should log that user in the database as "unknown/verifacation-failed" so it can take later action; next time they join it should try one more time in case the first one was an error (Either because of a mojang issue or an expired session) and send a chat message that says "If you are using paid Minecraft, please do /premium to fix your login, then rejoin". The players on my server don't seem to notice _anything_ that isn't fun or really annoying.

But from my experience using my current plugin the extra logging will improve the odds of it correctly logging them as cracked or premium.

Have I explained it in a way that makes sense and sounds viable? If not we can talk on spigot's teamspeak server.

**Comment by games647** [comment]
>Have I explained it in a way that makes sense and sounds viable? If not we can talk on spigot's teamspeak server.

Didn't know that they have teamspeak. I thought just a IRC. 

Okay I understand it then.

**Comment by lizardfreak321** [comment]
Are you planning on implementing this? If so, when? If you cannot do it soon I will fix my currently login plugin.

**Comment by games647** [comment]
Yes I'm going to implement it, but currently I very busy.

**Comment by Azfaloth** [comment]
I too am interested in this and I am in a similar situation as lizardfreak321.

When premium players join, I just want them to be auto registered and auto logged in without any fuss. If they fail the premium check, they should be asked to register etc.
Since I use server generated uuids anyway, that doesn't matter much to me but I would really like a config option with this functionality. Premium players don't like registering and typing commands etc to login. The less they know about a server being cracked, the better it is because most will just assume a cracked server is trash and leave which is quite unfortunate.

I feel only cracked players should be asked to register and so on. I hope you implement this feature at some point! Not sure if you remember but I requested this kind of system in the spigot forums a long time ago.

**Comment by games647** [comment]
I just refused it, because I really cannot change kick message of "Invalid session please restart your game" if it's a cracked player and we request a premium authentication.

**Comment by lizardfreak321** [comment]
Refused what?
I have spent a lot of time looking though and editing the BungeeCord source and this is my conclusion: If a player has a NON-canceled PreLoginEvent but no LoginEvent the odds are the kick reason is "Invalid session please restart your game", because the only thing that needs to get done between then is authentication of the player. The only other possible thing that could happen is it saying the auth servers are down, so it is a good idea to check if the mojang session/auth servers are online.
All version stuff is done before the pre-login-event (with the exception of maybe some version modification plugins).

**Comment by games647** [comment]
>Refused what?

This was for @Azfaloth 

@lizardfreak321 
yeah I know or the client pressed cancel, lost internet connection (wifi, cable). But yeah I'm going to implement it for 1.9 or earlier if there is pr. For 1.8 I'm planning to only add database importers (i.e. from AutoIn). That's not much work, because most of it is already implemented and available on Github. 

Then for 1.9 I'll start working on it right ahead. I don't think it will be much work since the data is only in memory like this:
1. Unknown player joining the server
2. Check if autoRegister is enabled
3. Add to an expiring cache
4. On next login request check if that player is in that cache
5. Remove the cache entry on successful join

BTW: I used http://wiki.vg/Protocol#Login a lot and wrote this little guide https://github.com/games647/FastLogin#online-mode to help others.

**Comment by games647** [comment]
Do you have any idea how I should name this feature?

**Comment by lizardfreak321** [comment]
I call it semipremium, but since this feature extends auto-register (I think, depending on how you are implementing it), I would put it as a sub-config option boolean that says "assume-premium", false being when this is enabled.

**Comment by Azfaloth** [comment]
True, but I'm glad that you are adding this now in this manner.

**Comment by Eufranio** [comment]
Would be cool if that feature have a config option to disable, i don't want that my players use a Premium account
If a premium players with a invalid session or a cracked client join and gets kicked, if he tries to join another time he will log in as cracked. If the owner of the premium account join, the cracked user will lose the account to the premium.
It's confusing, just add the option xD

**Comment by games647** [comment]
It already has.

**Comment by crashback-exe** [comment]
So has this been added?
