### ISSUE TITLE
How to force cracked server to use offline UUID while using Bungee Cord?

### ISSUE THREAD

**Issue by JCAguilera** [games647/FastLogin#539]
I have a server that uses FastLogin and premium uuids are set to false in FastLogin config. Now I want to set up Bungee with my server, but I want to use premium uuids everywhere except for that one server. Is there any option that I have to change so this can happend?

Bungee FastLogin config:

```
autoRegister: true
switchMode: true
premiumUuid: true
autoLogin: true
```

Cracked Server FastLogin config:

```
autoRegister: false
switchMode: false
premiumUuid: false
autoLogin: true
```

Hub Server FastLogin config:

```
autoRegister: true
switchMode: true
premiumUuid: true
autoLogin: true
```
I've also set allowed_proxies.txt in both servers.
Using this config, I can join the cracked server (with the offline uuid in the whitelist) but my uuid is changed to premium uuid, so my player lost the inventory and other configurations. Then I tried to remove the uuid from allowed_proxies, but when I try to join I get the "Not in whitelist" message.

What else can I do? Thanks for your help!

**Comment by games647** [comment]
BungeeCord forwards the UUID to the Spigot server to have consistency. Changes there of the premium UUID will be reflected on the Spigot servers. This is something that BungeeCord does internally. I wouldn't recommend overwriting it for specific server, because incoming data from that server then needs to be translated back to the original UUID. There is no concept in BungeeCord for that.
