### ISSUE TITLE
loadProfile(name) returns NULL on Bukkit side when using BungeeCord.

### ISSUE THREAD

**Issue by Maxetto** [games647/FastLogin#55]
Hi, I'm trying to catch whenever a player is Premium or not when chatting in order to identify them with a Prefix.

I'm using this function to hook into the Plugin and it's working fine on both BungeeCord and Spigot:
FastLoginBukkit plugin = (FastLoginBukkit) Bukkit.getPluginManager().getPlugin("FastLogin")

And this function to get whether a player is Premium or not (Inside AsyncPlayerChatEvent):
plugin.getCore().getStorage().loadProfile(e.getPlayer().getName()).isPremium()

This last function works fine with BungeeCord and with Spigot when "bungeecord: false".

This is the error I get:
http://pastebin.com/MmX3qbZC

Using:
Spigot 1.8.8
BungeeCord 1.7-1.8
FastLogin Commit-6c1c4e7

**Comment by Maxetto** [comment]
There are also those 2 errors on Bungee's StartUp (Changes already done and re-applied on every startup?):
http://pastebin.com/4ciGVjhV

**Comment by Maxetto** [comment]
It seems that when BungeeCord is detected, the plugin doesn't even load the Database in the Bukkit side.

How can I send the request to the Bungee side of the Plugin, then?

**Comment by games647** [comment]
>And this function to get whether a player is Premium or not (Inside AsyncPlayerChatEvent):
plugin.getCore().getStorage().loadProfile(e.getPlayer().getName()).isPremium()

You don't get a NPE on loadProfile. getStorage() returns null if BungeeCord is enabled and this is intended for less configuration work and produce less stress on the MySQL database. So there is only one management component which takes care of it.

>There are also those 2 errors on Bungee's StartUp (Changes already done and re-applied on every startup?):
http://pastebin.com/4ciGVjhV

You can ignore those errors. See the logging level. They are just used for debugging. Sadly there is no safe way to drop and create a new index without producing a new error.

>How can I send the request to the Bungee side of the Plugin, then?

The plugin currently communicates over plugin-channels and it then sets a bukkit metadata field. You can make use of it. (although it's set before the proxy-key validation)

BTW: I'm thinking of removing proxy-key validation, because if FastLogin started up correctly in BungeeCord it will prevent fake messages from hackers.

**Comment by Maxetto** [comment]
Could you give me an example on how to request if someone is Premium to the BungeeSide and how to receive the answer?

**Comment by games647** [comment]
Make an extra BungeeCord plugin and communicate over plugin-channels. Register the channel and define a custom protocol message. Something like

YourPlugin
IsPremium
Playername

read the message on the bungeecord side and then start a database query. You could also use the sessions, because the sessions in BungeeCord only expire on disconnect. After you got a result send the result back over the plugin-channel something like this:

YourPlugin
PremiumCheck
PlayerName
boolean

**Comment by Maxetto** [comment]
Ok, I think I got it.

**Comment by Maxetto** [comment]
I solved the problem by Listening for FastLogin "AUTO_LOGIN" plugin messages and adding those users to an ArrayList.

If the list contains the name, the player is Premium (as being Auto-Logged in), otherwise is Cracked. :stuck_out_tongue_closed_eyes:
