### ISSUE TITLE
[Suggestion] Command to convert the database

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#64]
If a server is running with SQLite database, the data are stored in the SQLite file. Would be cool a option/command to convert the SQLite database into the new MySQL database configured in the config. So, if you type /convertdb, it will automatically send the data from SQLite to MySQL configured.

**Comment by ljacqu** [comment]
I believe `/authme convert sqlitetosql` does exactly this. Just start with MySQL configured as connection and run the command.

**Comment by games647** [comment]
I'm more a friend of doing it manually, because then the user knows what's going on. You can do that within one minute, so it's not that hard and time expensive. 

By forcing users to do it manually, users gain important experience. I think it's better for the server managment if someone is able to monitor and manage basic stuff of the database. That might be helpful for finding solutions for other problems and fixing it on your own. This can be a lot faster than developer can respond to you.

**Comment by Eufranio** [comment]
So... no?

**Comment by games647** [comment]
Is it really so important?

**Comment by Eufranio** [comment]
At least for me yes, users are crazy to steal cracked accounts ATM...

**Comment by games647** [comment]
You could easily export the data using SQLiteMan to .sql file and then import it to a MySQL database.

**Comment by games647** [comment]
and how should they steal the account? FastLogin checks if that account already exists.

**Comment by Eufranio** [comment]
Thank you, and i'm currently not using auth plugins by a while, to fix some issues with my bungee network, the only db they have is FastLogin...
