### ISSUE TITLE
Cracked players with Tlauncher can't Join

### ISSUE THREAD

**Issue by BlueTree242** [games647/FastLogin#671]
### What happened?

When someone cracked joins it says Invalid session (Try restart launcher) but the weird point is that this doesn't happen when you go cracked on a hack client

### What did you expect?

Player is kicked if they new, else they join peacefully

### Steps to reproduce

Enable autoRegister and secondAttemptCracked and enable switchMode too

Join with Tlauncher, you get this message

If you use a hack client to go cracked, it goes fine

### Configuration file

https://pastebin.com/ch9kCpwk

### Plugin version

1.11-SNAPSHOT-5612ca7

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
This likely because of the autoRegister feature.

Quote
```yml
# Furthermore the premium player check have to be made based on the player name
# This means if a cracked player connects to the server and we request a paid account login from this player
# the player just disconnect and sees the message: 'bad login' or 'invalid session'
# There is no way to change this message
```

**Comment by Polda18** [comment]
Autoregister performs a check if the player name has a valid username in Mojang's database (paid account). If there is such account, then FastLogin assumes this player is the owner of that account and is currently playing while logged in to that account from the game (just to clarify, TLauncher also supports Mojang login, not sure about Microsoft login, so if a player logs in to their Mojang account on TLauncher, they should be able to join online mode servers, therefore they should be able to join servers with this configuration). As stated, it works pretty much like on online mode servers. ProtocolLib provides API library for FastLogin that activates sort of proxy server that fakes the server being online mode, but it only does when Premium access is specifically requested. If the player connects with a cracked client, but his username exists in Mojang database, the plugin looks it up and sees that the player name exists in database and assumes it's a legitimate player. Therefore it requests authentication from Mojang servers and there it fails, because the player obviously isn't logged in. That may happen far more frequently than you would think, because there's a lot of players that bought the game and there's just a high chance that a cracked player just coincidentally picks a username of another player that bought the game. This is a common issue and autoregister therefore isn't a recommended option.

**Comment by BlueTree242** [comment]
why are you explaining what protocolib do, i already do know. Protocolib does not fake anything, but simmilar, It modifies the actual packet classes using reflections before they are sent to client.

**Comment by BlueTree242** [comment]
can it not request paid on those who are in db and were not changed to premium

**Comment by games647** [comment]
>ProtocolLib provides API library for FastLogin that activates sort of proxy server that fakes the server being online mode

To clarify ProtocolLib only provides a method to create and modify packets. The fake onlinemode is implemented on FastLogin's side.

>Protocolib does not fake anything, but simmilar, It modifies the actual packet classes using reflections before they are sent to client.

It can also create packets. This is what FastLogin uses. FastLogin re-implements the onlinemode protocol by sending additional packets. This is why offline mode is required, so that vanilla servers don't send those packets. 

>can it not request paid on those who are in db and were not changed to premium

If autoRegister is disabled, FastLogin only requests online mode connections from those who opt in using the `/premium` command. At login we only receive the username and the connection details (IP, date/time, etc.) and have to make a decision at that time. 

> That may happen far more frequently than you would think, because there's a lot of players that bought the game and there's just a high chance that a cracked player just coincidentally picks a username of another player that bought the game. This is a common issue and autoregister therefore isn't a recommended option.

That's why autoRegister is disabled by default.
