### ISSUE TITLE
Error between FastLogin and Floodgate (paper 1.18)

### ISSUE THREAD

**Issue by Danifoxe** [games647/FastLogin#672]
### What happened?

When starting Fastlogin, having the geyser and floodgate plugins, an error message appears and fastlogin is deactivated. 

Paper version git-Paper-36 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 76ee105)

### What did you expect?

Normal startup of both Fastlogin, Geyser and Floodgate. 

### Steps to reproduce

Have Fastlogin, Geyser and Floodgate on the same server paper 1.18. 

### Plugin list

Plugins (28): AuthMe, BuycraftX, CoreProtect, DiscordSRV, dynmap, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, FastLogin, floodgate, Geyser-Spigot, GPRealEstate, GriefPrevention, GriefPreventionDynmap*, GriefPreventionFlags, GSit, LuckPerms, Parties, ProtocolLib, Quests, QuickShop, SkinsRestorer, TimeVote, Vault, Votifier, VotingPlugin, WorldEdit

### Configuration file

https://www.toptal.com/developers/hastebin/enaxuzocob.yaml

### Server log

```shell
https://www.toptal.com/developers/hastebin/ezixekuzew.md
```

### Plugin version

1.11-SNAPSHOT-95251b6

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Smart123s** [comment]
The Geyser API was updated: https://github.com/GeyserMC/Geyser/wiki/Using-Geyser-or-Floodgate-as-a-dependency/_compare/7110301b7486b068eb685c4e4220b05cd18d80f5

I'll update FastLogin to use the new API as soon as I have some spare time. Support for the older API can be dropeed, because the Bedrock clients are always auto updated to the latest version, and they don't have a version selector.
