### ISSUE TITLE
FastLogin API to create auth plugin that is compatible with FastLogin?

### ISSUE THREAD

**Issue by Azfaloth** [games647/FastLogin#68]
Considering how many bugs AuthMe has and most of the auth plugins have far more complicated settings and features than I actually require, I have made my own auth plugin.

Do you have any API which I could use to make my plugin compatible with your plugin directly from my side? Can you link me to the appropriate section in your source or give a small example please?

**Comment by games647** [comment]
There is this method called [setAuthHook](https://github.com/games647/FastLogin/blob/master/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/FastLoginBukkit.java#L195) Please use this method and our own implemation of the interface [BukkitAuthPlugin](https://github.com/games647/FastLogin/blob/master/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/hooks/BukkitAuthPlugin.java). 

As you can see a lot of the stuff there is documented. If you need help, just ask. Example could you see in the hooks package. Here for example for [LogIt](https://github.com/games647/FastLogin/blob/master/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/hooks/LogItHook.java).

Warning: All methods there are called async. In order to prevent threading issues, you should either make your relevant code thread-safe or synchronize the calling thread with the main thread. 

An example to sychronize with the main thread is this for [xAuth](https://github.com/games647/FastLogin/blob/master/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/hooks/xAuthHook.java). I know this is a mess, but it's required to prevent bugs (i.e. race conditions) that are really hard to debug. I could help you with that if you want to.

Furthermore you should check that don't make nested callSyncMethod calls. That would cause a **dead lock. Example for a dead lock:**
1. [Async Thread] Async call to forceRegister
2. [Async Thread - Waiting on main thread result] Waiting for the main thread (with callSyncMethod) to call register method there
3. Now login the player. If you do that in the callSyncMethod block it's already running on the main thread. 
4. Main thread invokes second callSyncMethod in the forceLogin method and waits until a lock is released, but this lock is released only by the main thread. So it's busy waiting for an operation it should do after the callSyncMethod. 
5. Server crashes, because it stopped responding.

Because forceLogin can be also called async too. You should make forceLogin() call outside the callSyncMethod block. Example here: https://github.com/games647/FastLogin/blob/master/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/hooks/xAuthHook.java#L82

I hope I could help you and didn't confused you. Multi-threading is a big topic. Sorry...

**Comment by Azfaloth** [comment]
Thank you very much for your detailed response! While I am familiar with only some basics of multi threaded programming, I will go through all the examples, related documentation and read up about things that I do not yet know. I am sure it will be an interesting learning experience for me. I will let you know if I need any further help with it. Thank you once again for your friendly, quick and detailed response.!

**Comment by Azfaloth** [comment]
So it turns out that my plugin was thread safe and I didn't need to do anything to sync the threads. The plugin works well and is running on my live server since two days. I should have done this long ago rather than wait so long for authme lol. Thank you once again for your help!
