### ISSUE TITLE
More antibot features

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [games647/FastLogin#805]
Since the antibot plugins are not compatible with this plugin, can you tweak the fastlogin antibot a little?
1. IP whitelist, Kick players who join first time, and if they dont rejoin in 30 seconds do not whitelist them, and they must play for 2 minutes to be whitelisted.
2. Fix the existing antibot, after the limit is hit, registered premium players will join as cracked, i mean, already registered users should not be affected because they do not affect ratelimit.
3. Do not accept new connections for a time configured in config, after server get x connections in x minutes, and kick those who wanna to enter with the message "Server under attack".
4. The TPS drops too much if you are under bot attack, even with a decent CPU.

**Comment by TDMidkwhatisxd** [comment]
Or at least add an option, if antibot limit reached, just deny future connections until x minutes as set in config.

**Comment by games647** [comment]
>The TPS drops too much if you are under bot attack, even with a decent CPU.

Please make a timings report with the corresponding anti bot configuration of FastLogin. FastLogin will drop any processing if it reaches the anti bot limit. So this could be likely a different plugin.

>IP whitelist, Kick players who join first time, and if they dont rejoin in 30 seconds do not whitelist them, and they must play for 2 minutes to be whitelisted.

This can be your anti bot plugin. FastLogin should only be responsible for logins. The simple anti bot feature drops any load, so that even no database connections are established.

>Fix the existing antibot, after the limit is hit, registered premium players will join as cracked, i mean, already registered users should not be affected because they do not affect ratelimit.

How should the plugin react otherwise? The main load of FastLogin are the interactions with third-parties. Namely:

* HTTP-Connection to Mojang for verification or if `autoRegister` is enabled
    * If rate-limited (600 req per 10min), we can no longer ask for the UUID and `autoRegister` gets temporarily disabled. So only verification like a normal onlinemode will be used.
* Force login handling: Request the auth plugin to force login
* Database request to check if the player is premium

The first two are not the issue, because it only gets enabled after a premium connection has been requested similar to a **normal onlinemode server**. The anti bot feature then targets the last step the database. It's the ground base to make all of these decisions.

>Do not accept new connections for a time configured in config, after server get x connections in x minutes, and kick those who wanna to enter with the message "Server under attack".

Anti bot plugins do that. We are not responsible for that. If FastLogin drops its processing, the anti bot plugin can do anything it wants.

**Comment by TDMidkwhatisxd** [comment]
After a bot attack, if players cant use the autologin feature, the plugin is useless. Even if i have antibot, the fastlogin is the first to receive connections.
At least block any connection (enabled by config), some plugins glitch if uuid change.

**Comment by games647** [comment]
> Cant be done by antibots, since no antibot go over fastlogin.

There are anti bot plugins that listen to FastLogin and cancel them for this reason.

>After a bot attack, if players cant use the autologin feature, the plugin is useless.

Well it expires, this is a very strict implementation for the case that your server cannot handle the database load, which should be very fast to begin with.

**Comment by TDMidkwhatisxd** [comment]
can you tell me what should i use?

**Comment by TDMidkwhatisxd** [comment]
> > Cant be done by antibots, since no antibot go over fastlogin.
> 
> There are anti bot plugins that listen to FastLogin and cancel them for this reason.
> 
> > After a bot attack, if players cant use the autologin feature, the plugin is useless.
> 
> Well it expires, this is a very strict implementation for the case that your server cannot handle the database load, which should be very fast to begin with.

Yes, but could as well, just deny any connection (enabled by config), until it expires. It just makes my life harder.
