### ISSUE TITLE
Does not auto-register when someone is already in the fastlogin database.

### ISSUE THREAD

**Issue by lizardfreak321** [games647/FastLogin#85]
When someone is marked as premium on the database, it assumes they are already registered in the login plugin (AuthMe in my case). However if they are not registered for any reason (In my case I needed to add them to the fastlogin database from the old plugin), or if they change their name it will try to log them in but the force-login will fail due to them not being registered.

If this plugin could check if the account exists before it auto-logs them in, it could register those without an account with a randomly generated password like it does to new players.

(Players are complaining about this, and some users have gone past their account per IP limit so this will really help my server)

**Comment by games647** [comment]
This is intended, because it makes more sense to either import all the data to the new auth plugin or start both plugins from a new database. 

Because if the database of an auth plugin is empty, we cannot know if it's really the same person behind that player name. The old password authentication is gone and so it could be a new person who just chose to have the same username as an old player on your server. 

I think this can happen very often with popular playernames.

**Comment by lizardfreak321** [comment]
I get your point, but in the case of premium authenticated players we can assume that it is the same person. I'm not saying cracked players should be auto-registered, I'm just saying premium players should.
