### ISSUE TITLE
Server is not fully started yet. Please retry 

### ISSUE THREAD

**Issue by pawelkuwa** [games647/FastLogin#980]
### What happened?

I installed latest build of ```FastLogin``` https://ci.codemc.io/job/Games647/job/FastLogin/1192/ and ProtocolLib 5.0.0 and it still doesn't work

lastest.log
https://pastebin.com/raw/hyt1vJLt

### What did you expect?

works fastlogin fine

### Steps to reproduce

install lastest fastlogin build and protocollib 5.0.0

### Plugin list

FastLogin, ProtocolLib, SkinsRestorer

### Configuration file

https://pastebin.com/PLXRhvvZ

### Server log

https://pastebin.com/raw/hyt1vJLt

### Plugin version

v1.12-SNAPSHOT-971b0e1

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
It says it in the server log:

[00:46:27] [Server thread/WARN]: [FastLogin] No support offline Auth plugin found. 
[00:46:27] [Server thread/WARN]: [FastLogin] No auth plugin were found by this plugin (other plugins could hook into this after the initialization of this plugin)and BungeeCord is deactivated. Either one or both of the checks have to pass in order to use this plugin

**Comment by pawelkuwa** [comment]
so how can i hook fastlogin to my own plugin and make fastlogin supporting my plugin for correctly load?
i did depend fastlogin to my plugin.yml in my plugin and it still doesn't works

**Comment by pawelkuwa** [comment]
and after add to soft-depend fastlogin plugin.yml my own plugin still it shows 
![image](https://user-images.githubusercontent.com/83598982/215609839-bf94d916-5ee1-48d1-94ab-993776dc8244.png)
![image](https://user-images.githubusercontent.com/83598982/215609865-7d60edf4-45ca-43e4-9b96-eff7f87c01ab.png)

**Comment by games647** [comment]
You don't need to modify FastLogin, but you have to register your hook here: https://github.com/games647/FastLogin/blob/971b0e1f09cd8a0281931c4e782fbc0950c480cb/core/src/main/java/com/github/games647/fastlogin/core/shared/FastLoginCore.java#L292

After FastLogin loaded, but before the world ticks (is fully loaded). Furthermore, I see your auth plugin is not loaded in the server log. It needs to be installed in order to use it.

**Comment by pawelkuwa** [comment]
test class https://pastebin.com/dzMSZkwu
main class https://pastebin.com/Lv7Qc7fe

and it shows
https://pastebin.com/BpAE8xgE

**Comment by games647** [comment]
The error means that fastlogin isn't installed. You need to have both installed.

**Comment by pawelkuwa** [comment]
fastlogin are installed 
https://pastebin.com/XimZQthw

**Comment by pawelkuwa** [comment]
maybe i did it incorrect? i mean test class and main class

**Comment by games647** [comment]
You are initializing the `fastLoginBukkit` field during class initialization not during the `onEnable` method. The class file is loaded for Java yet at this instant.
